core/urls.py
from core import views
from django.urls import path

app_name="core"

urlpatterns=[
    path("",views.welcome,name="welcome"),
    path('send-message/', views.send_message, name='send_message'),
]

home/urls.py
from home import views
from django.urls import path

app_name="home"

urlpatterns=[
    path("",views.home,name="home"),
    path("loading...",views.loading,name="loading"),
    path("map",views.mapview,name="map"),
]

userauths/urls.py
from userauths import views
from django.urls import path

app_name="userauths"

urlpatterns=[
    path('sign-up/',views.register_view,name='sign-up'),
    path('sign-in/',views.login_view,name='sign-in'),
    path('sign-out/',views.logout_view,name='sign-out'),
]

wildfire/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include('userauths.urls')),
    path('',include('core.urls')),
    path('home/',include('home.urls')),
]

urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

home/forms.py
from django import forms

class ImageUploadForm(forms.Form):
    image = forms.ImageField()

home/views.py
from django.shortcuts import render,redirect
from datetime import datetime
from home.api_calls.weatherAPI import get_weather_data
from django.views.decorators.csrf import csrf_exempt
from home.AI_Model.ai_train import predict_fire

from django.conf import settings
import os

from .forms import ImageUploadForm
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from django.conf import settings
from email.mime.image import MIMEImage
from userauths.models import User

def send_wildfire_result_email(user_emails, result, image_path):
    subject = 'Wildfire Detection Result'
    from_email = settings.EMAIL_HOST_USER
    
    for user_email in user_emails:
        to_email = user_email.email  # Assuming 'email' is the field name
        html_content = render_to_string('home/app/email.html', {'result': result})
        
        msg = EmailMultiAlternatives(subject, '', from_email, [to_email])
        msg.attach_alternative(html_content, "text/html")
        
        # Attach the uploaded image
        with open(image_path, 'rb') as f:
            img = MIMEImage(f.read())
            img.add_header('Content-ID', '<uploaded_image>')
            img.add_header('Content-Disposition', 'inline', filename=os.path.basename(image_path))
            msg.attach(img)
        
        msg.send()

#----------------------------------------------------------------------------
def kelvin_to_celsius(kelvin):
    return kelvin - 273.15

def unix_to_human_readable(unix_time):
    return datetime.utcfromtimestamp(unix_time).strftime('%Y-%m-%d %H:%M:%S')
#----------------------------------------------------------------------------

@csrf_exempt
def loading(request):
    if request.method == "POST":
        latitude = request.POST.get('latitude')
        longitude = request.POST.get('longitude')
        weather_data = get_weather_data(latitude, longitude)
        
        request.session['weather_data'] = weather_data
        request.session['latitude'] = latitude
        request.session['longitude'] = longitude
        return redirect("home:home")
    else:
        latitude = 22.7179
        longitude = 75.8333
    return render(request, 'home/app/loading_page.html')

def home(request):
    weather_data = request.session.get('weather_data')
    latitude = request.session.get('latitude')
    longitude = request.session.get('longitude')
    image_filename = None
    result=0

    # Convert temperatures to Celsius
    weather_data['main']['temp'] = kelvin_to_celsius(weather_data['main']['temp'])
    weather_data['main']['feels_like'] = kelvin_to_celsius(weather_data['main']['feels_like'])

    # Convert Unix time to human-readable format
    weather_data['sys']['sunrise'] = unix_to_human_readable(weather_data['sys']['sunrise'])
    weather_data['sys']['sunset'] = unix_to_human_readable(weather_data['sys']['sunset'])

    if request.method == 'POST':
        form = ImageUploadForm(request.POST, request.FILES)
        if form.is_valid():
            image = form.cleaned_data['image']
            image_filename = image.name
            image_path = os.path.join(settings.MEDIA_ROOT, image.name)
            
            with open(image_path, 'wb+') as destination:
                for chunk in image.chunks():
                    destination.write(chunk)
            
            result = predict_fire(image_path)
            user_emails = User.objects.all()  # Assuming User is your model
            print(image_filename)
            send_wildfire_result_email(user_emails, result, image_path)
    else:
        form = ImageUploadForm()
        
    context = {
        'form':form,
        'result': result,
        'weather_data': weather_data,
        'longitude': longitude,
        'latitude': latitude,
        'image_path': image_filename,
    }
    return render(request, 'home/app/home.html', context)

def mapview(request):
    latitude = request.session.get('latitude')
    longitude = request.session.get('longitude')
    api_key = 'WeDkOLJgAzvafGXb9MVB'
    context = {
        'longitude': longitude,
        'latitude': latitude,
        'api_key_map': api_key,
    }
    return render(request, 'home/app/map.html', context)

home/templates/home/app/email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Wildfire Detection Results</title>
    <style>
        .result-container {
            margin: 20px;
            text-align: center;
        }
        .result-card {
            margin-top: 20px;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        .fire {
            color: red;
        }
        .no-fire {
            color: green;
        }
        .image-preview {
            max-width: 100%;
            height: auto;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
    </style>
</head>
<body>
    <div style="background-color: #f4f4f4; padding: 20px;">
        <img style="width: 100%;align-self: center;" src="cid:logo_image" alt="Website Logo">
        <h1 style="color: #333; text-align: center;">Wildfire Detection Result</h1>
        <h2 style="color: #333; text-align: center;">Here is the result of your uploaded image:</h2>
        <hr style="border-top: 1px solid #999;">
        <div class="result-container">
            <div class="card result-card">
                <img src="cid:uploaded_image" alt="Uploaded Image" class="image-preview mb-4">
                {% if result == 'Fire' %}
                    <h3 class="fire">Alert: Fire Detected!</h3>
                    <p>The uploaded image shows signs of fire. Please take necessary precautions immediately.</p>
                    <p>Contact emergency services and follow safety protocols to ensure everyone's safety.</p>
                {% else %}
                    <h3 class="no-fire">No Fire Detected</h3>
                    <p>The uploaded image does not show any signs of fire. Stay vigilant and safe.</p>
                    <p>Ensure regular checks and maintain safety measures to prevent any fire hazards.</p>
                {% endif %}
            </div>
        </div>
        <hr style="border-top: 1px solid #999;">
        <p style="text-align: center; color: #777;">Thank you for using our service!</p>
    </div>
</body>
</html>

home/templates/home/app/loading_page.html
{% extends 'home/partial/base.html' %}
{% load static %}

{% block index %}

<div class="loader">
    <div class="three-body">
        <div class="three-body__dot"></div>
        <div class="three-body__dot"></div>
        <div class="three-body__dot"></div>
    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(function (position) {
                var latitude = position.coords.latitude;
                var longitude = position.coords.longitude;

                // Create a form and submit the latitude and longitude
                var form = document.createElement("form");
                form.setAttribute("method", "post");
                form.setAttribute("action", "/home/loading...");

                var latInput = document.createElement("input");
                latInput.setAttribute("type", "hidden");
                latInput.setAttribute("name", "latitude");
                latInput.setAttribute("value", latitude);
                form.appendChild(latInput);

                var lonInput = document.createElement("input");
                lonInput.setAttribute("type", "hidden");
                lonInput.setAttribute("name", "longitude");
                lonInput.setAttribute("value", longitude);
                form.appendChild(lonInput);

                // Add CSRF token input
                var csrfToken = "{{ csrf_token }}";
                var csrfInput = document.createElement("input");
                csrfInput.setAttribute("type", "hidden");
                csrfInput.setAttribute("name", "csrfmiddlewaretoken");
                csrfInput.setAttribute("value", csrfToken);
                form.appendChild(csrfInput);

                document.body.appendChild(form);
                form.submit();
            }, function (error) {
                console.error("Error getting location: ", error);
            });
        } else {
            console.error("Geolocation is not supported by this browser.");
        }
    });
</script>

{% endblock index %}

home/templates/home/app/map.html
{% extends 'home/partial/base.html' %}
{% load static %}

{% block index %}
<!-- map js -->
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
<script src="https://cdn.maptiler.com/maptiler-sdk-js/v2.0.3/maptiler-sdk.umd.js"></script>
<script src="https://cdn.maptiler.com/leaflet-maptilersdk/v2.0.0/leaflet-maptilersdk.js"></script>

<!-- navbar -->
<div class="navbar sticky" id="navbar">
  <div class="logo">
      <a href="#" style="font-size: 20px;">Wildfire</a>
  </div>
  <div class="nav-links pc-navlinks">
      <a href="{% url 'userauths:sign-out' %}">Logout</a>
      <a href="{% url 'home:map' %}">Map</a>
      <a href="{% url 'home:home' %}">Home</a>
  </div>
  <div class="nav-links mobile-navlinks">
      <a href="#">Login</a>
      <a href="{% url 'home:map' %}">Map</a>
      <a href="{% url 'home:home' %}">Home</a>
  </div>

  <div class="mobile-menu-toggle">
      <div class="hamburger-menu">
          <div class="bar"></div>
          <div class="bar"></div>
          <div class="bar"></div>
      </div>
  </div>
</div>
<script>
  document.querySelector('.hamburger-menu').addEventListener('click', function () {
      var links = document.querySelector(".mobile-navlinks");
      var hamburger = document.querySelector(".hamburger-menu");
      if (links.style.display === "flex") {
          links.style.display = "none";
          hamburger.classList.remove("cross");
      } else {
          links.style.display = "flex";
          hamburger.classList.add("cross");
      }
  });
</script>
<div id="result" style="padding-top: 70px;">

</div>

<div id="map"></div>
<script>
  const key = 'WeDkOLJgAzvafGXb9MVB';
  const map = L.map('map').setView([{{latitude}}, {{longitude}}], 14);
  const mtLayer = L.maptilerLayer({
    apiKey: key,
    style: "hybrid", //optional
  }).addTo(map);
</script>


{% endblock index %}