core/urls.py
from core import views
from django.urls import path

app_name="core"

urlpatterns=[
    path("",views.welcome,name="welcome"),
    path('send-message/', views.send_message, name='send_message'),
]

userauths/urls.py
from userauths import views
from django.urls import path

app_name="userauths"

urlpatterns=[
    path('sign-up/',views.register_view,name='sign-up'),
    path('sign-in/',views.login_view,name='sign-in'),
    path('sign-out/',views.logout_view,name='sign-out'),
]

wildfire/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include('userauths.urls')),
    path('',include('core.urls')),
    path('home/',include('home.urls')),
]

urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

def user_directory_path(instance,filename):
    return 'user_{0}/{1}'.format(instance,filename)

class TeamModel(models.Model):
    name=models.CharField(max_length=100)
    branch=models.CharField(max_length=100)
    year=models.CharField(max_length=100)
    role=models.CharField(max_length=100)
    image=models.ImageField(upload_to=user_directory_path,default="default.png")

core/views.py
from django.shortcuts import render
from core.models import TeamModel

from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import json
import os

# chatbot
import streamlit as st
from dotenv import load_dotenv
import os
import google.generativeai as genai

# Load environment variables
load_dotenv()

# Configure Google Gemini Pro API
genai.configure(api_key=os.getenv("GOOGLE_API_KEY"))

# Prompt for the GenerativeModel
prompt = """You are the safety advisor specialized in forest fires, wildfires, and disaster management. 
Provide essential tips and information on prevention, safety protocols during emergencies. 
Concise tips within 250 words. Answer questions related to fire safety and disaster management."""

# Function to generate content using Gemini Pro
def generate_gemini_content(transcript_text, prompt):
    model = genai.GenerativeModel("gemini-pro")
    response = model.generate_content(prompt + transcript_text)
    return response.text

def welcome(request):
    teamdetails=TeamModel.objects.all()
    context={
        'teamdetails':teamdetails,
    }
    return render(request,'core/app/welcome.html',context)

@csrf_exempt
def send_message(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        user_message = data.get('message', '')
        if user_message:
            response_message = generate_gemini_content(user_message, prompt)
            return JsonResponse({"reply": response_message})
        return JsonResponse({"reply": "I didn't understand that. Could you please rephrase?"})
    return JsonResponse({"error": "Invalid request method."}, status=405)

core/templates/core/app/welcome.html
{% extends 'core/partial/base.html' %}
{% load static %}

{% block index %}

<div class="navbar" id="navbar">
    <div class="logo">
        <a href="#" style="font-size: 20px;">Wildfire</a>
    </div>
    <div class="nav-links pc-navlinks">
        <a href="{% url 'userauths:sign-in' %}">Login</a>
        <a href="#Team">Team</a>
        <a href="#contact">Contact</a>
    </div>
    <div class="nav-links mobile-navlinks">
        <a href="#">Login</a>
        <a href="#Team">Team</a>
        <a href="#contact">Contact</a>
    </div>

    <div class="mobile-menu-toggle">
        <div class="hamburger-menu">
            <div class="bar"></div>
            <div class="bar"></div>
            <div class="bar"></div>
        </div>
    </div>
</div>
<script>
    document.querySelector('.hamburger-menu').addEventListener('click', function () {
        var links = document.querySelector(".mobile-navlinks");
        var hamburger = document.querySelector(".hamburger-menu");
        if (links.style.display === "flex") {
            links.style.display = "none";
            hamburger.classList.remove("cross");
        } else {
            links.style.display = "flex";
            hamburger.classList.add("cross");
        }
    });
</script>

<div class="container-fluid row" style="position: fixed;height: 100vh;top: 0;padding: 0;">
    <div class="back-contain col-md-7">
        {% include "core/elements/background.html" %}
    </div>
    <div class="container welcome-info col-md-5">
        <h1 style="font-weight: 800;">Welcome to Wildfire Prevention</h1>
        <p>Explore the Information and tools <br>regarding wildfire preventions.</p>
        <a href="{% url 'userauths:sign-in' %}" class="cta-button" style="z-index: 999;">Explore Now</a>
    </div>
</div>
<div class="space" style="height: 100vh;z-index: -10;pointer-events: none;"></div>
<!-- other contents -->
<div class="container-fluid" style="background-color: white;margin-top: 80px;position: sticky;
box-shadow: 0px -1px 5px rgba(255, 255, 255, 1.00),
  0px -2px 20px rgba(255, 255, 255, 1.00),
  0px -5px 46px rgba(255, 255, 255, 1.00),
  0px -8px 82px rgba(255, 255, 255, 1.00),
  0px -13px 128px rgba(255, 255, 255, 1.00),
  0px -18px 184px rgba(255, 255, 255, 1.00);
">

    <section class="container-fluid">
        <div class="row" style="padding-top: 30px;">
            <div class="col-md-6 fireprevent h-100">
                <img src="../../../static/core/image/fireprevent.jpeg" alt="" style="max-height: 400px;">
            </div>
            <div class="col-md-6">
                <h2 style="color: #7c2e08;font-weight: 700;">Why Wildfire Prevention ?</h2>
                <p style="padding-top: 0;">Preventable wildfires are a significant concern due to their impact on lives,
                    property, and natural resources. Here’s why wildfire prevention matters:</p>
                <li>Human-Caused Fires: 87 percent of all wildfires are caused by human activities1. Most of these fires
                    can be avoided through responsible behavior.</li>
                <li>Threat to Lives and Property: Wildfires endanger communities, homes, and infrastructure. Preventing
                    them reduces the risk of loss and harm.</li>
                <li>Preserving Natural Resources: Forests, wildlife habitats, and ecosystems are at risk during
                    wildfires. Prevention helps protect our environment.</li>
            </div>
        </div>
    </section>
    <br><br>
    <h2 class="mt-4" style="text-align: center;color: #7c2e08;font-weight: 700;">About Team</h2>
    <section class="container-fluid">

        <div class="row mt-4" id="Team">
            {% for teamdetail in teamdetails %}
            <div class="col-md-4" style="background-color: transparent;">
                <div class="card contro-card" style="width: 100%;background-color: transparent;">
                <img src="{{ teamdetail.image.url }}" class="card-img-top" alt="">
                <div class="card-body">
                    <h5 class="card-title">{{ teamdetail.name }}</h5>
                    <a href="#" class="btn contro-btn">{{ teamdetail.branch }}</a>
                    <a href="#" class="btn contro-btn">{{ teamdetail.year }}</a>
                    <a href="#" class="btn contro-btn">{{ teamdetail.role }}</a>
                </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </section>
    <section class="container-fluid">
        <div id="form">
            <form action="" id="contact">
                <div class="col-md-12">
                    <h2>Contact Form</h2>
                    <div class="mb-3">
                        <label for="exampleFormControlInput1" class="form-label">Email address</label>
                        <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
                    </div>
                    <div class="mb-3">
                        <label for="exampleFormControlTextarea1" class="form-label">Example textarea</label>
                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"
                            placeholder="Enter the Message..."></textarea>
                    </div>
                </div>
            </form>
        </div>
    </section>
</div>
{% endblock index %}