core/urls.py
from core import views
from django.urls import path

app_name="core"

urlpatterns=[
    path("",views.welcome,name="welcome"),
    path('send-message/', views.send_message, name='send_message'),
]

userauths/urls.py
from userauths import views
from django.urls import path

app_name="userauths"

urlpatterns=[
    path('sign-up/',views.register_view,name='sign-up'),
    path('sign-in/',views.login_view,name='sign-in'),
    path('sign-out/',views.logout_view,name='sign-out'),
]

wildfire/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include('userauths.urls')),
    path('',include('core.urls')),
    path('home/',include('home.urls')),
]

urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

userauths/models.py
from enum import unique
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db import models
from PIL import Image
from django.db.models.signals import post_save

class User(AbstractUser):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=100)
    bio = models.CharField(max_length=100)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    # Add related_name to avoid clashes with auth.User
    groups = models.ManyToManyField(
        "auth.Group",
        related_name="userauths_user_set",
        blank=True,
        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
        verbose_name="groups",
    )
    
    user_permissions = models.ManyToManyField(
        "auth.Permission",
        related_name="userauths_user_set",
        blank=True,
        help_text="Specific permissions for this user.",
        verbose_name="user permissions",
    )

    def __str__(self):
        return self.username
    
def user_directory_path(instance,filename):
    return 'user_{0}/{1}'.format(instance.user.id,filename)

class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    full_name=models.CharField(max_length=100)
    bio=models.CharField(max_length=100)
    image=models.ImageField(upload_to=user_directory_path,default="default.png")

    def __str__(self):
        try:
            return f"{self.full_name}-{self.user.username}-{self.user.email}"
        except:
            return self.user.username
        
    def save(self,*args,**kwargs):
        super().save(*args,**kwargs)
        img=Image.open(self.image.path)
        if img.height>300 or img.width>300:
            output_size=(300,300)
            img.thumbnail(output_size)
            img.save(self.image.path)


def create_user_profile(sender,instance,created,**kwargs):
    if created:
        Profile.objects.create(user=instance)

def save_user_profile(sender,instance,**kwargs):
    instance.profile.save()

post_save.connect(create_user_profile,sender=User)
post_save.connect(save_user_profile,sender=User)

userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from userauths.models import User

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

userauths/views.py
from django.shortcuts import render, redirect
from userauths.forms import UserRegisterForm
from django.contrib.auth import login, authenticate
from django.contrib import messages
from django.conf import settings
from django.contrib.auth import logout

User=settings.AUTH_USER_MODEL

def register_view(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST or None)
        if form.is_valid():
            new_user = form.save()
            username = form.cleaned_data.get("username")
            messages.success(request, f"Hey {username}, your account was created successfully")

            new_user = authenticate(username=form.cleaned_data['email'], 
                                    password=form.cleaned_data['password1'])
            
            login(request, new_user)
            return redirect("home:loading")
    else:
        form=UserRegisterForm()

    context = {
        'form': form,
    }
    return render(request, 'userauths/app/sign-up.html', context)

def login_view(request):
    if request.user.is_authenticated:
        messages.warning(request,f"Hey, You are already Logged in")
        return redirect('home:loading')
    else:
        if request.method=="POST":
            email=request.POST.get("email")
            password=request.POST.get("password")

            try:
                user=User.object.get(email=email)
            except:
                messages.warning(request,f"User with {email} does not exist")

            user=authenticate(request,email=email,password=password)

            if user is not None:
                login(request,user)
                messages.success(request,"Your are logged in.")
                return redirect("home:loading")
            
            else:
                messages.warning(request,"User Does not exist, create an accounnt")
    return render(request,"userauths/app/sign-in.html")


def logout_view(request):
    logout(request)
    messages.success(request, "You Logged-Out, successfully")
    return redirect("userauths:sign-in")

userauths/templates/userauths/app/sign-in.html
{% extends 'userauths/partial/base.html' %}
{% load static %}

{% block index %}
<div class="container sign-in-container 100vh">
    <div class="main-container">
        <div class="main-content">
            <div class="form-container">
                <div class="form-content box flex">
                    <div class="logo">
                        <img width="100px" src="../../../static/userauths/images/fire.png" alt="wildfire logo" class="logo-light">
                    </div>
                    <form method="POST" autocomplete="off">
                        {% csrf_token %}
                        <div class="signin-form" id="signin-form">
                            <div class="form-group">
                                <div class="animate-input">
                                    <span>
                                        Enter email
                                    </span>
                                    <input autocomplete="off" class="login-signup-input" type="text" name="email" maxlength="100" required="" id="login_username">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="animate-input">
                                    <span>
                                        Enter Password
                                    </span>
                                    <input autocomplete="off" class="login-signup-input" type="password" name="password" autocomplete="current-password" required="" id="login_password">
                                    <button>Show</button>
                                </div>
                            </div>
                            <div class="btn-group">
                                <button class="btn-login" id="signin-btn" type="submit">
                                    Sign In
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="box goto">
                    <p>
                        Don't have an account?
                        <a href="{% url 'userauths:sign-up' %}">Sign up</a>
                    </p>
                </div>

            </div>
        </div>
    </div>
    <div class="footer">
        <div class="links">
            <a href="#">About</a>
            <a href="#">Blog</a>
            <a href="#">Help</a>
            <a href="#">Privacy</a>
            <a href="#">Terms</a>
            <a href="#">Locations</a>
            
        </div>
        <div class="copyright">
            &copy; 2024 Wildfire. All Rights Reserved.
        </div>
    </div>
</div>

{% endblock index %}

userauths/templates/userauths/app/sign-up.html
{% extends 'userauths/partial/base.html' %}
{% load static %}

{% block index %}
<div class="container">
    <div class="main-container">
        <div class="main-content">
            <div class="form-container">
                <div class="form-content box">
                    <div class="logo">
                        <img width="100px" src="../../../static/userauths/images/fire.png" alt="wildfire logo" class="logo-light">
                    </div>


                    <form method="POST" autocomplete="off">
                        {% csrf_token %}
                        <div class="signin-form" id="signin-form">
                            <div class="form-group">
                                <div class="animate-input">
                                    <span>
                                        Enter Username
                                    </span>
                                    <input autocomplete="off" class="login-signup-input" type="text" name="username" maxlength="100" required id="id_username">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="animate-input">
                                    <span>
                                        Enter email
                                    </span>
                                    <input autocomplete="off" class="login-signup-input" type="email" name="email" maxlength="320" required id="id_email">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="animate-input">
                                    <span>
                                        Enter Password
                                    </span>
                                    <input class="login-signup-input" type="password" name="password1" autocomplete="new-password" required aria-describedby="id_password1_helptext" id="id_password1">
                                    <button>Show</button>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="animate-input">
                                    <span>
                                        Enter confirm Password
                                    </span>
                                    <input class="login-signup-input" type="password" name="password2" autocomplete="new-password" required aria-describedby="id_password2_helptext" id="id_password2">
                                    <button>Show</button>
                                </div>
                            </div>
                            <div class="btn-group">
                                <button class="btn-login" id="signin-btn" type="submit">
                                    Sign Up
                                </button>
                            </div>
                            
                            
                        </div>
                    </form>


                </div>
                <div class="box goto">
                    <p>
                        have an account?
                        <a href="{% url 'userauths:sign-in' %}">Sign in</a>
                    </p>
                </div>

            </div>
        </div>
    </div>
    <div class="footer">
        <div class="links">
            <a href="#">About</a>
            <a href="#">Blog</a>
            <a href="#">Help</a>
            <a href="#">Privacy</a>
            <a href="#">Terms</a>
            <a href="#">Locations</a>
            
        </div>
        <div class="copyright">
            &copy; 2024 Wildfire. All Rights Reserved.
        </div>
    </div>
</div>

{% endblock index %}